import {
  LayoutDashboard,
  Landmark,
  CreditCard,
  Receipt,
  FileText,
  AlertTriangle,
  BookOpen,
  Calculator,
  DollarSign,
  TrendingUp,
  BarChart3,
  Users,
  Contact,
  Building2,
  Network,
  ArrowLeftRight,
  Combine,
  Briefcase,
  ClipboardCheck,
  FileCheck,
  Settings,
  Shield,
  Wallet,
  Upload,
  CalendarDays,
  Percent,
  PiggyBank,
  Lock,
  Sparkles,
  Wand2,
  FlaskConical,
  History,
  Inbox,
  Activity,
  Banknote,
  Search,
  SlidersHorizontal,
  Scale,
  ShieldCheck,
  ClipboardList,
  type LucideIcon,
} from 'lucide-react';

export interface NavItem {
  label: string;
  href: string;
  icon: LucideIcon;
  badge?: string;
}

export interface NavGroup {
  label: string;
  items: NavItem[];
}

export const navigation: NavGroup[] = [
  {
    label: 'Overview',
    items: [
      { label: 'Dashboard', href: '/dashboard', icon: LayoutDashboard },
    ],
  },
  {
    label: 'Process',
    items: [
      { label: 'Action Inbox', href: '/inbox', icon: Inbox },
      { label: 'Needs Attention', href: '/exceptions', icon: Inbox },
      { label: 'Bank Feed', href: '/bank-feed', icon: Landmark },
      { label: 'Credit Cards', href: '/credit-cards', icon: CreditCard },
      { label: 'Receipts', href: '/receipts', icon: Receipt },
      { label: 'Bills', href: '/bills', icon: FileText },
      { label: 'AP Intake', href: '/bills/intake-queue', icon: Inbox },
      { label: 'Purchase Orders', href: '/purchase-orders', icon: ClipboardList },
      { label: 'Expenses', href: '/expenses', icon: Wallet },
      { label: 'Expense Policy', href: '/expenses/policy', icon: ClipboardCheck },
      { label: 'AP Policy', href: '/bills/policy', icon: ClipboardCheck },
      { label: 'Check Run', href: '/checks', icon: Banknote },
      { label: 'Flagged Items', href: '/flagged', icon: AlertTriangle },
    ],
  },
  {
    label: 'Financial',
    items: [
      { label: 'Journal Entries', href: '/journal-entries', icon: BookOpen },
      { label: 'Recurring Entries', href: '/recurring-journal-entries', icon: History },
      { label: 'Chart of Accounts', href: '/chart-of-accounts', icon: Calculator },
      { label: 'Reconciliation', href: '/reconciliation', icon: FileCheck },
      { label: 'Leases', href: '/leases', icon: Landmark },
      { label: 'Prepaids', href: '/prepaids', icon: Wallet },
      { label: 'Insurance', href: '/insurance', icon: ShieldCheck },
      { label: 'Intangibles', href: '/intangibles', icon: Calculator },
      { label: 'Fiscal Periods', href: '/periods', icon: CalendarDays },
      { label: 'Revenue Recognition', href: '/rev-rec', icon: Percent },
      { label: 'Invoices', href: '/invoices', icon: DollarSign },
      { label: 'Cash Application', href: '/cash-application', icon: Banknote },
      { label: 'Collections', href: '/collections', icon: Contact },
      { label: 'Payments', href: '/settings/payments', icon: CreditCard },
      { label: 'Payroll', href: '/payroll', icon: Wallet },
      { label: 'Budgets', href: '/budgets', icon: BarChart3 },
      { label: 'Driver Budget', href: '/budgets/drivers', icon: TrendingUp },
      { label: 'Reforecast', href: '/budgets/reforecast', icon: TrendingUp },
    ],
  },
  {
    label: 'Intelligence',
    items: [
      { label: 'Search', href: '/search', icon: Search },
      { label: 'Cash Position', href: '/cash', icon: Wallet },
      { label: '13-Week Forecast', href: '/forecast', icon: TrendingUp },
      { label: 'Covenant Monitor', href: '/covenants', icon: ShieldCheck },
      { label: 'Debt & Loans', href: '/debt', icon: Landmark },
      { label: 'Subscriptions', href: '/subscriptions', icon: CreditCard },
      { label: 'Renewals & Obligations', href: '/obligations', icon: CalendarDays },
      { label: 'Reports', href: '/reports', icon: BarChart3 },
      { label: 'FP&A Dashboard', href: '/fpna', icon: BarChart3 },
      { label: 'Board Package', href: '/board-package', icon: FileText },
      { label: 'Profitability', href: '/profitability', icon: TrendingUp },
      { label: 'AI Decision Log', href: '/ai-decisions', icon: Sparkles },
      { label: 'AI Categorizer', href: '/categorize', icon: Wand2 },
    ],
  },
  {
    label: 'Operations',
    items: [
      { label: 'Departments', href: '/departments', icon: Network },
      { label: 'Internal Invoices', href: '/internal-invoices', icon: ArrowLeftRight },
      { label: 'Intercompany', href: '/intercompany', icon: Combine },
      { label: 'Consolidation', href: '/consolidation', icon: Building2 },
      { label: 'Jobs & Projects', href: '/jobs', icon: Briefcase },
      { label: 'Job WIP Schedule', href: '/jobs/wip', icon: ClipboardCheck },
      { label: 'Vendors', href: '/vendors', icon: Building2 },
      { label: 'Customers', href: '/customers', icon: Contact },
      { label: 'Retainage', href: '/retainage', icon: PiggyBank },
      { label: 'Vendor Compliance', href: '/vendor-compliance', icon: Shield },
      { label: '1099 Readiness', href: '/compliance-1099', icon: FileCheck },
      { label: 'Book-to-Tax (M-1)', href: '/book-to-tax', icon: Scale },
      { label: 'Tax Provision (ASC 740)', href: '/tax-provision', icon: Percent },
      { label: 'Sales Tax Return', href: '/sales-tax-return', icon: Landmark },
      { label: 'Tax Depreciation', href: '/tax-depreciation', icon: Calculator },
      { label: 'Close Management', href: '/close', icon: ClipboardCheck },
      { label: 'Close Command Center', href: '/close-status', icon: Activity },
      { label: 'Year-End Close', href: '/year-end-close', icon: Lock },
    ],
  },
  {
    label: 'Practice',
    items: [
      { label: 'Team & Access', href: '/team', icon: Users },
      { label: 'Audit Trail', href: '/audit', icon: History },
      { label: 'Operations', href: '/operations', icon: Activity },
      { label: 'Companies', href: '/settings', icon: Building2 },
      { label: 'Compliance', href: '/compliance', icon: Shield },
      { label: 'Controls / SOX', href: '/controls', icon: ShieldCheck },
      { label: 'Documents', href: '/documents', icon: FileText },
      { label: 'Import Data', href: '/import', icon: Upload },
      { label: 'Historical Conversion', href: '/onboarding/conversion', icon: Upload },
      { label: 'Sandbox', href: '/sandbox', icon: FlaskConical },
      { label: 'AI Autonomy', href: '/settings/autonomy', icon: SlidersHorizontal },
      { label: 'Settings', href: '/settings', icon: Settings },
    ],
  },
  {
    label: 'Platform',
    items: [
      { label: 'Operator Console', href: '/platform', icon: Building2 },
    ],
  },
];
