/**
 * Create a debt instrument and generate its amortization schedule.
 *
 * The confirm path: validated terms in (bigint cents), an instrument row + the full
 * deterministic amortization schedule out. The schedule is generated by the pure
 * `buildAmortizationSchedule` and persisted line-by-line. Runs on the RLS-scoped
 * client, so org isolation is enforced by the database. If the terms can't produce
 * a schedule (e.g. a payment that never amortizes) it throws before anything
 * persists — the caller returns a 422 and nothing is written.
 */

import type { SupabaseClient } from '@supabase/supabase-js';
import {
  buildAmortizationSchedule,
  AmortizationError,
  type AmortizationSchedule,
} from './amortization';
import type { CreateDebtInput } from './schema';
import { recordDebtOrigination } from './posting';

type DB = SupabaseClient;

export interface CreateDebtResult {
  id: string;
  schedule: AmortizationSchedule;
}

export interface CreateDebtOptions {
  /**
   * Post the origination JE (DR Cash / CR Notes Payable) after persisting. Default
   * true. The refinance path passes false — it books the liability itself via a
   * rollover entry, so an origination post there would double-credit the liability.
   */
  postOrigination?: boolean;
}

export async function createDebtInstrument(
  db: DB,
  orgId: string,
  userId: string | null,
  input: CreateDebtInput,
  opts: CreateDebtOptions = {},
): Promise<CreateDebtResult> {
  // Build the schedule FIRST — if the terms are impossible, fail before any write.
  const schedule = buildAmortizationSchedule({
    principalCents: input.principal_cents,
    annualRatePercent: input.interest_rate,
    frequency: input.payment_frequency,
    method: input.amortization_method,
    termPeriods: input.term_periods ?? null,
    paymentCents: input.payment_cents ?? null,
    originationDate: input.origination_date ?? null,
  });

  const { data: inst, error: instError } = await db
    .from('debt_instruments')
    // Column names reconcile onto the EXISTING migration-008 table:
    //   loan_name -> name, principal_cents -> original_amount_cents,
    //   payment_cents -> monthly_payment_cents,
    //   liability_account_id -> gl_liability_account_id,
    //   interest_expense_account_id -> gl_interest_account_id.
    // current_balance_cents opens at the original principal; instrument_type is left
    // to its column default ('OTHER') since the feature doesn't collect it.
    .insert({
      org_id: orgId,
      location_id: input.location_id ?? null,
      name: input.loan_name,
      lender: input.lender ?? null,
      facility: input.facility ?? null,
      original_amount_cents: input.principal_cents,
      current_balance_cents: input.principal_cents,
      interest_rate: input.interest_rate,
      rate_type: input.rate_type,
      amortization_method: input.amortization_method,
      payment_frequency: input.payment_frequency,
      compounding: input.compounding,
      term_periods: input.term_periods ?? schedule.periods,
      monthly_payment_cents: input.payment_cents ?? schedule.regularPaymentCents,
      origination_date: input.origination_date ?? null,
      maturity_date: input.maturity_date ?? null,
      status: input.status,
      loan_covenant_id: input.loan_covenant_id ?? null,
      gl_liability_account_id: input.liability_account_id ?? null,
      gl_interest_account_id: input.interest_expense_account_id ?? null,
      interest_payable_account_id: input.interest_payable_account_id ?? null,
      cash_account_id: input.cash_account_id ?? null,
      notes: input.notes ?? null,
      created_by_user: userId,
    })
    .select('id')
    .single();

  if (instError || !inst) {
    throw new AmortizationError(`Failed to create debt instrument: ${instError?.message ?? 'unknown'}`);
  }
  const instrumentId = (inst as { id: string }).id;

  const lineRows = schedule.lines.map((l) => ({
    org_id: orgId,
    instrument_id: instrumentId,
    period: l.period,
    period_date: l.periodDate,
    payment_cents: l.paymentCents,
    interest_cents: l.interestCents,
    principal_cents: l.principalCents,
    principal_balance_cents: l.principalBalanceCents,
  }));

  const { error: linesError } = await db.from('debt_schedule_lines').insert(lineRows);
  if (linesError) {
    // Roll back the instrument so we never leave a scheduleless shell.
    await db.from('debt_instruments').delete().eq('id', instrumentId);
    throw new AmortizationError(`Failed to write amortization schedule: ${linesError.message}`);
  }

  // Recognize the loan on the GL at origination: DR Cash / CR Notes Payable for the
  // principal (idempotent per instrument). Fail CLOSED — if the GL can't accept the
  // opening entry (e.g. no fiscal period), roll the whole instrument back rather than
  // leave a subledger register that can never tie to the GL control account.
  if (opts.postOrigination !== false) {
    try {
      await recordDebtOrigination(db, { orgId, instrumentId, userId });
    } catch (e) {
      await db.from('debt_schedule_lines').delete().eq('instrument_id', instrumentId);
      await db.from('debt_instruments').delete().eq('id', instrumentId);
      throw e;
    }
  }

  return { id: instrumentId, schedule };
}
