/**
 * Create a debt instrument and generate its amortization schedule.
 *
 * The confirm path: validated terms in (bigint cents), an instrument row + the full
 * deterministic amortization schedule out. The schedule is generated by the pure
 * `buildAmortizationSchedule` and persisted line-by-line. Runs on the RLS-scoped
 * client, so org isolation is enforced by the database. If the terms can't produce
 * a schedule (e.g. a payment that never amortizes) it throws before anything
 * persists — the caller returns a 422 and nothing is written.
 */

import type { SupabaseClient } from '@supabase/supabase-js';
import {
  buildAmortizationSchedule,
  AmortizationError,
  type AmortizationSchedule,
} from './amortization';
import type { CreateDebtInput } from './schema';

type DB = SupabaseClient;

export interface CreateDebtResult {
  id: string;
  schedule: AmortizationSchedule;
}

export async function createDebtInstrument(
  db: DB,
  orgId: string,
  userId: string | null,
  input: CreateDebtInput,
): Promise<CreateDebtResult> {
  // Build the schedule FIRST — if the terms are impossible, fail before any write.
  const schedule = buildAmortizationSchedule({
    principalCents: input.principal_cents,
    annualRatePercent: input.interest_rate,
    frequency: input.payment_frequency,
    method: input.amortization_method,
    termPeriods: input.term_periods ?? null,
    paymentCents: input.payment_cents ?? null,
    originationDate: input.origination_date ?? null,
  });

  const { data: inst, error: instError } = await db
    .from('debt_instruments')
    .insert({
      org_id: orgId,
      location_id: input.location_id ?? null,
      loan_name: input.loan_name,
      lender: input.lender ?? null,
      facility: input.facility ?? null,
      principal_cents: input.principal_cents,
      interest_rate: input.interest_rate,
      rate_type: input.rate_type,
      amortization_method: input.amortization_method,
      payment_frequency: input.payment_frequency,
      compounding: input.compounding,
      term_periods: input.term_periods ?? schedule.periods,
      payment_cents: input.payment_cents ?? schedule.regularPaymentCents,
      origination_date: input.origination_date ?? null,
      maturity_date: input.maturity_date ?? null,
      status: input.status,
      loan_covenant_id: input.loan_covenant_id ?? null,
      liability_account_id: input.liability_account_id ?? null,
      interest_expense_account_id: input.interest_expense_account_id ?? null,
      interest_payable_account_id: input.interest_payable_account_id ?? null,
      cash_account_id: input.cash_account_id ?? null,
      notes: input.notes ?? null,
      created_by_user: userId,
    })
    .select('id')
    .single();

  if (instError || !inst) {
    throw new AmortizationError(`Failed to create debt instrument: ${instError?.message ?? 'unknown'}`);
  }
  const instrumentId = (inst as { id: string }).id;

  const lineRows = schedule.lines.map((l) => ({
    org_id: orgId,
    instrument_id: instrumentId,
    period: l.period,
    period_date: l.periodDate,
    payment_cents: l.paymentCents,
    interest_cents: l.interestCents,
    principal_cents: l.principalCents,
    principal_balance_cents: l.principalBalanceCents,
  }));

  const { error: linesError } = await db.from('debt_schedule_lines').insert(lineRows);
  if (linesError) {
    // Roll back the instrument so we never leave a scheduleless shell.
    await db.from('debt_instruments').delete().eq('id', instrumentId);
    throw new AmortizationError(`Failed to write amortization schedule: ${linesError.message}`);
  }

  return { id: instrumentId, schedule };
}
